(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e;if("function"==typeof Object.setPrototypeOf)e=Object.setPrototypeOf;else{var f;a:{var g={f:!0},h={};try{h.__proto__=g;f=h.f;break a}catch(a){}f=!1}e=f?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var k=e,l=function(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(k)k(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var m=Object.getOwnPropertyDescriptor(b,c);m&&Object.defineProperty(a,c,m)}else a[c]=b[c];a.g=b.prototype};var p=function(){var a=HTMLElement.call(this)||this;a.video=null;a.a=0;a.b=function(){a.a<=a.getTime()&&n(a);a.a=a.video.duration};a.c=function(){return a.handleVideoTimeUpdate()};a.resizeHandlerNeeded=!1;return a};l(p,HTMLElement);
p.prototype.connectedCallback=function(){var a=this.parentElement;a&&a.interactiveVideoComponents&&(this.video=a,this.video.interactiveVideoComponents.push(this),this.video.setResizeObserver(),this.video.addEventListener("ended",this.b,!1),this.video.addEventListener("timeupdate",this.c,!1))};
p.prototype.disconnectedCallback=function(){if(this.video&&this.video.interactiveVideoComponents){var a=this.video.interactiveVideoComponents.indexOf(this);-1!=a&&this.video.interactiveVideoComponents.splice(a,1);this.video.setResizeObserver();this.video.removeEventListener("ended",this.b,!1);this.video.removeEventListener("timeupdate",this.c,!1)}this.video=null};p.prototype.resize=function(){};var n=function(a){var b=void 0===b?null:b;var c=document.createEvent("CustomEvent");c.initCustomEvent("cuepoint",!0,!0,b);a.dispatchEvent(c)};var q=function(){return p.call(this)||this};l(q,p);q.prototype.seek=function(){this.video.seek(this.getTime())};q.prototype.getTime=function(){var a=this.getAttribute("time");return a?parseFloat(a):0};q.prototype.setTime=function(a){this.setAttribute("time",Math.max(a,0))};
q.prototype.handleVideoTimeUpdate=function(){this.video.nativeElement.seeking||this.a==this.video.currentTime||(this.video.loop&&.25>this.video.currentTime&&this.a>=this.video.duration-.25&&(this.a<=this.getTime()||this.getTime()<this.video.currentTime)?n(this):this.a<=this.getTime()&&this.getTime()<this.video.currentTime&&n(this),this.a=this.video.currentTime)};customElements.define("gwd-cuepoint",q);}).call(this);
