console.log("studio invocation script");
function studioInvocation() {
    Enabler.setProfileId(10584246);
    var devDynamicContent = {};

    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed = [{}];
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0]._id = 0;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].id = 10;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].Reporting_Label = "5fc0e86a64c78300064827be-5fc8b878e322390006fb151a_55";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].Active = true;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].Weights = 1;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].Scoring_status = "Unscored";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].animationType = "frame1";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].logo = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].logo.Url = "https://cdn.ad-lib.io/v2/partners/5c5578a2e50cb95de10c079e/assets/single-files/image/png/eb837116c62e9d9c8a60b1ca56d07761/specsavers_300x431.png";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].baseImage = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].baseImage.Url = "https://cdn.ad-lib.io/v3/partners/5c5578a2e50cb95de10c079e/assets/singleFiles/5fc103a564c7830006484926/original/Specs_EcommCL_300x431%402x.png";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline = "Etsitk&ouml; piilolinssej&auml;?";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline2 = "Valitse piilolinssit laajasta valikoimastamme";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline3 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline = "Valikoima,&nbsp;<br \/>joka palvelee kaikkia tarpeitasi";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline2 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline3 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline2 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline3 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].currency = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Image = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Image.Url = "https://cdn.ad-lib.io/v2/partners/5c5578a2e50cb95de10c079e/assets/single-files/image/png/152d175dde739a79e9397f1373ad1fa6/blank.png";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaText = "Osta nyt";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaText2 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaColor1 = "White";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaColor2 = "N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize1 = "25, 18, 0";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize2 = "25, 0, 0";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize3 = "0, 0, 0";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor1 = "White, White, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor2 = "White, White, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor3 = "N\/A, N\/A, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable = "Bold, Medium, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable2 = "Bold, Medium, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable3 = "N\/A, N\/A, N\/A";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgMask1 = "Racing";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgMask2 = "White";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgColor = "White";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].cssAttrib = "#curveWrapper{height: 262px !important;}#frame1-headline2{margin-bottom:-10px;}";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].landingPage = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].landingPage.Url = "https://www.specsavers.fi/piilolinssit?utm_medium=social&utm_source=facebook&utm_campaign=fi_01_01_0_other_specs-no-offer_ao-rtg&utm_term=tana_rtg";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].startDate = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].startDate.RawValue = "12/28/2020";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].startDate.UtcValue = 1609113600000;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].endDate = {};
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].endDate.RawValue = "03/08/2021";
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].endDate.UtcValue = 1615161600000;
    devDynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].readableLabel = "Retargeting A";
    Enabler.setDevDynamicContent(devDynamicContent);
    
    
  defaultValues.animationType = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].animationType;
  defaultValues.logo = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].logo.Url;
  defaultValues.frame1Headline = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline;
  defaultValues.frame1Headline2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline2;
  defaultValues.frame1Headline3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Headline3;
  defaultValues.frame2Headline = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline;
  defaultValues.frame2Headline2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline2;
  defaultValues.frame2Headline3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame2Headline3;
  defaultValues.frame3Headline = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline;
  defaultValues.frame3Headline2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline2;
  defaultValues.frame3Headline3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame3Headline3;
  defaultValues.baseImage = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].baseImage.Url;
  defaultValues.frame1Image = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Image.Url;
  //defaultValues.frame1Background = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].frame1Background.Url;
  defaultValues.currency = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].currency;
  defaultValues.ctaText = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaText;
  defaultValues.ctaText2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaText2;
  defaultValues.ctaColor1 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaColor1;
  defaultValues.ctaColor2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].ctaColor2;
  defaultValues.fontSize1 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize1;
  defaultValues.fontSize2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize2;
  defaultValues.fontSize3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontSize3;
  defaultValues.fontColor1 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor1;
  defaultValues.fontColor2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor2;
  defaultValues.fontColor3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].fontColor3;
  defaultValues.customVariable = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable;
  defaultValues.customVariable2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable2;
  defaultValues.customVariable3 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].customVariable3;
  defaultValues.bgMask1 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgMask1;
  defaultValues.bgMask2 = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgMask2;
  defaultValues.cssAttrib = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].cssAttrib;
  defaultValues.bgColor = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].bgColor;
  defaultValues.landingPage = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].landingPage.Url;
/*defaultValues.startDate = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0]
  defaultValues.endDate = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0] */
  defaultValues.readableLabel = dynamicContent.FI_01_01_0_Other_Specs_no_offer_AO_RTG_Ecomm_CL_AdLib_Feed[0].readableLabel;
}